{% set name = "ipython-memory-usage" %}
{% set version = "1.2" %}
{% set sha256 = "1f4697210257f853fea74de0cf3fae60a32e550e578bac6f46de9b40c550422b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - ipython


test:
  imports:
   - ipython_memory_usage

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: BSD2
  license_family: BSD
  license_file: LICENSE
  summary:
    - IPython tool to report memory usage deltas for every command you type. If you are running out of RAM then use this tool to understand what’s happening. It also records the time spent running each command.
    - In [3]: arr=np.random.uniform(size=int(1e7))
    -   ‘arr=np.random.uniform(size=int(1e7))’ used 76.2578 MiB RAM in 0.33s, peaked 0.00 MiB above current, total RAM usage 107.37 MiB

extra:
  recipe-maintainers:
    - ianozsvald
    - ps-git
