{% set name = "ipython_memory_usage" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b19d8952c8cc8be1e59b5850ba55c16394c0efb7f14427205a25ebd54aa3f265

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipython >=7.0
    - memory_profiler
    - psutil

test:
  requires:
    - pip
    - python {{ python_min }}
  files:
    - test_import.py
  commands:
    - python -m IPython test_import.py
    - pip check

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: MIT
  license_file: LICENSE
  summary: |
    IPython tool to report memory usage deltas for every command you type.
    If you are running out of RAM then use this tool to understand what’s
    happening. It also records the time spent running each command.

extra:
  recipe-maintainers:
    - xhochy
    - ianozsvald
