{% set name = "ipython_memory_usage" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/60/e5/6e437102cf49c3843c8f192c7c7b99184e5946930bb9ab0e23799e802586/ipython_memory_usage-1.2.tar.gz
  sha256: 1704ada665410f0443052efc108f4c8819c60bb7b0d6e7b253a098f0a66284d0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - memory_profiler
    - ipython

test:
  imports:
    - datetime
    
    #ipython_memory_usage

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'IPython tool to report memory usage deltas for every command you type'
  dev_url: https://github.com/ianozsvald/ipython_memory_usage

extra:
  recipe-maintainers:
    - xhochy
    - ianozsvald
