{% set name = "ipython_memory_usage" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76912d35dc57a6a9dd1158c0e80da5d6a703cbed876bdb8b6390d6f9aa719946

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - ipython

test:
  commands:
    - python -m IPython "import ipython_memory_usage"

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    IPython tool to report memory usage deltas for every command you type.
    If you are running out of RAM then use this tool to understand what’s
    happening. It also records the time spent running each command.

extra:
  recipe-maintainers:
    - xhochy
    - ianozsvald
    - ps-git

