{% set name = "ipython_memory_usage" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 962d544904608ab6db0b61246f728fb71b86df5798975478b5239d33b17fd725

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - ipython

test:
  commands:
    - python -m IPython "import ipython_memory_usage"

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    IPython tool to report memory usage deltas for every command you type.
    If you are running out of RAM then use this tool to understand what’s
    happening. It also records the time spent running each command.

extra:
  recipe-maintainers:
    - xhochy
    - ianozsvald
    - ps-git

