{% set name = "ipython_memory_usage" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1704ada665410f0443052efc108f4c8819c60bb7b0d6e7b253a098f0a66284d0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - ipython

test:
  commands:
    - python -m IPython "import ipython_memory_usage"

about:
  home: https://github.com/ianozsvald/ipython_memory_usage
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    IPython tool to report memory usage deltas for every command you type.
    If you are running out of RAM then use this tool to understand what’s
    happening. It also records the time spent running each command.

extra:
  recipe-maintainers:
    - xhochy
    - ianozsvald
    - ps-git
    
