travis:
  secure:
    BINSTAR_TOKEN: QjiTBJp91fyALDNPkrjQHJT0UN2IlKvk3WHAPB1h6O94kpYZOq8KEMrQNGi4Yv78QJZL0/YGpoCciFTpt7YSCjvUVZ2qE7TySnrAQ/LoUWDTHEUEkwUNw6++ih7tLpXtb+iY8rWEEn3u3cRYFRmL0JbyfgtqhKf+X/rBLY9Nveizlb2OIM+oZMgZcE1y0813twLcmwEuuCofbCBCQWXpxg+7yZAwbMjZmXP3wbxXk7jWwxw/cS+QCS+HMDwH9maMEOFkGs1WrG8Y1y+GRH2C/gfaXxS3+zUPCZMGWpvEqk7ysJYg/VVD3ZnMlImHJSN55sUPA96hFGj3QDr6vwd1Kakf7GzHg+okEu/rR81nb9U8dbpZeLa4pZP9RlNFRIBpQbIwtPBJXM5jmmvadBAah9nkAM+rsojG1qwrZdMQNoz6raWzw6uYdaV0ofgf8tFYFEN61z/7lvyxTl8Yh/xpm/pf4mX7gsmza6/ZbABr8hf/cbv7kqa+pNMdA8DklHdRxbPhE6rwuTzkCEN6qfYS2K+a+Nm6Ujb81x5mmgAw7S3hWK7bv3hsJf50fDxKK5oCmec8blEzDXNzHYzerIhDQSDmWYrfTfK6wh518/YMWZj3vIQ6/MIcMUi0q04eob1I6D5N+F7CHd6pXE/uFoB6Gm/Hf3x4rkaQjdetoeuOHvg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
